### ISSUE TITLE
[İSTEK] SSS sayfası

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/front-end#11]
# Özellik isteği
SSS Page react helmet ile og ve twitter card + sss page de yazılan yazıları nasıl renklendirebilirim yazıyı.

## Aşağıdakileri doğruluyorum:
- [ ] Sistemde böyle bir özelliğin olup olmadığını buraya yazmadan önce araştırdım.

**Comment by ayberktandogan** [comment]
Ne demek istediğinizi anlamadım.

**Comment by Hime-Dev** [comment]
SSS page de og veya twitter dataları yok seo için iyi olabilir. 

Diğer dediğim ise sss page de .env üzerinden yazıyoruz direk metin olarak alıyor belirli yerlerini renkli yapmak istiyorum bunu nasıl yapabilirim. atıyorum sss page in 2. satın 3. cümlesini sarı renginde olsun gibi
