### ISSUE TITLE
[HATA] Manga linklerinde manga cover_art'ı büyük gözüküyor.

### ISSUE THREAD

**Issue by ayberktandogan** [ForFansubs/front-end#14]
# Hata raporu

## Sistem Bilgisi
- Kullandığınız işletim sistemi - Windows 10
- front-end versiyonu - v2.5.0

## Aşağıdakileri doğruluyorum:
- [x] Kodda kendi değiştirdiğim bir şey yüzünden aldığım bir hata değil.
- [x] front-end'in son versiyonunu kullanıyorum.

## Sorunlar
 - Ne yapmaya çalışıyorsunuz?: Manga linkini Discord gibi yerlere attığım zaman manga resminin küçük gözükmesini sağlamaya çalışıyorum.
- Ne olmasını istiyorsunuz?: Manga resminin küçük gözükmesini istiyorum.
- Ne oluyor?: Manga resmi büyük kalıyor.

**Comment by Hime-Dev** [comment]
og:types: books.book yapınca düzeliyor.

**Comment by ayberktandogan** [comment]
https://github.com/ForFansubs/front-end/releases/tag/v2.6.0

**Comment by Hime-Dev** [comment]
teşekkürler. Öncelikli olarak front-admin de ki sistem hatasını düzeltirseniz sevinirim.
