### ISSUE TITLE
[İSTEK] MOTD / İçerik Bildirim

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/front-end#21]
# Özellik isteği
Duyuru Sistemi
## Özellik ayrıntıları
Header da ki logonun sağ kısmından veya giriş yap işaretinin sol kısmından başlayarak sağdan sola veya soldan sağa admin sisteminden özelleştirilebilir duyuru penceresi bu sistemde yazının kayma sistemi ile birden çok duyuru yapılabilir demek istediğim admin sisteminden "," koyarak bir çok duyuru girebileceğiz ve gösterim süresini oradan ayarlayacağız 5 dk bir dediğimiz zaman 5 dk da bir sırasıyla duyuruları gösterecek. (Bu özellik yapılırsa lütfen her sitedeki gibi sağdan sola kan bir şekilde değilde normal sabit ve  yukardan veya aşağıdan yukarı değişik bir kaybolma efekti kullanılsa güzel olur siteye farklı bir hava katacağını düşünüyorum.)
## Aşağıdakileri doğruluyorum:
- [x] Sistemde böyle bir özelliğin olup olmadığını buraya yazmadan önce araştırdım.

**Comment by ayberktandogan** [comment]
ForFansubs/node-server#24
