### ISSUE TITLE
🌸 v3.*.* Yol Haritası

### ISSUE THREAD

**Issue by ayberktandogan** [ForFansubs/front-end#25]
# v3.\*.\* Yol Haritası

Bu konu kapatılana kadar https://github.com/ForFansubs/front-end/tree/dev üzerinde devam eden değişiklikleri ele alacak.

## Çıkış tarihi
Temmuz 2020.

## Önemli duyurular 💥💥💥
- 2.\*.\* versiyonlarında, React 17.*'a güncellenmeyecek.
- 3.\*.\* versiyonuna tam olarak geçiş yapıldığında, 2.\*.\* versiyonu için ayrı bir branch açılıp, `master` branchi 3.\*.\*'a geçirilecek.

## Önemli Değişiklikler (v2.\*.\* --> v3.\*.\*) 💔
- `react-slick` paketi kaldırıldı.
- `react-helmet` paketi kaldırıldı. Yerine `react-helmet-async` paketi eklendi.
- `styled-components` paketi kaldırıldı.

## Güncellemeler
- İzleme sayfasında bölüm izleme linklerinin bulunduğu kutucuğun giriş ve çıkış animasyonları CSS üzerinden verildiği için animasyon sağlıklı gösterilemiyordu. Bu animasyon, React'a bağlanarak düzeltildi.
- `react-helmet` paketi, bağlı olduğu bir paketin kullandığı bir React methodu yüzünden konsolda hata gösteriyordu, ve React 17.*'de çalışmayacağını belirtiyordu. Bu yüzden `react-helmet-async` paketi ile değiştirildi. (#26 'yı çözer.)
- Sayfalardaki useTheme() methodları kaldırıldı.
- `styled-components` paketi kaldırıldı. Bütün sayfalardaki stiller, `@material-ui/core` paketinin parçası olan makeStyles() methoduna bağlandı, buna bağlı olarak tekrardan yazıldı.
- Genel tema ayarları `/src/config/theming/index.js`e taşındı. Light ve Dark özel ayarlar, kendi dosyalarında bırakıldı.

## Yenilikler
- Öne çıkarılmış animeler kısmının tasarım değişikliği. #24 
- Header tasarım değişikliği. 
- Anime ve manga sayfalarının tasarım güncellemeleri. #35
- Ana sayfa tasarım güncellemeleri. #39 
- Footer'a link eklemek için özel bir dosya oluşturuldu. `/src/config/footer_items.js`
- Drawer'a link eklemek için özel bir dosya oluşturuldu. `/src/config/drawer_items.js`
- Manga okuma özelliği/sayfası. #38
- Anime sayfasında toplu linklerin en üstte gözükmesi. #35
- Ana sayfa / içeriklere özel duyuru alanları. #21 

## Bilinen hatalar
- ~Mobilde scroll bar gözüküyor.~
- ~404 sayfayının konumu yanlış.~
- ~public dosyasına logo.png atılması gerekiyor. Dökümanlarda düzeltme lazım.~
- Manga okuma sayfasında okuma türü değiştirilirse, global state'te alınmış diğer ayarlar siliniyor.

**Comment by Hime-Dev** [comment]
react helmetin 512.png değiştirilmeyi unutulmuş.

**Comment by ayberktandogan** [comment]
![screencapture-localhost-3000-1585755922425](https://user-images.githubusercontent.com/42430762/78166900-34cbc380-7456-11ea-8a7a-dbe74071477e.png)
![screencapture-localhost-3000-1585755909672](https://user-images.githubusercontent.com/42430762/78166903-35645a00-7456-11ea-939b-6ef4c9f117f7.png)

**Comment by Hime-Dev** [comment]
güzel olmuş fakat toplu linkler yazısı ortada kalsa daha güzel olabilir hep her şey sol tarafa atılmış gibi duruyor
