### ISSUE TITLE
[GÜNCELLEME] Drawer

### ISSUE THREAD

**Issue by ayberktandogan** [ForFansubs/front-end#27]
# Drawer Güncellemesi

Yandan çıkan, ana ekrana bağlı çalışan bir `Drawer`. Footer'da bu `Drawer` içerisinde gösterilecek.

---------------
![screencapture-localhost-3000-1585060773910](https://user-images.githubusercontent.com/42430762/77438445-e172c900-6df6-11ea-9540-faa13b77df10.png)

**Comment by Hime-Dev** [comment]
Buda çok güzel duruyor ellerine sağlık fakat  footer kısmını admin panelinde ki sisteme bağlayıp ekstra bilgi eklenebilen bir şey yapabilir misin veya tema dosyalarında olan extra.js gibi bir şey bazı güncellemeler de gidiyor ekstra eklediklerimizi tekrar yazmak gerekiyor.
