### ISSUE TITLE
[GÜNCELLEME] Öne Çıkarılmış Animeler

### ISSUE THREAD

**Issue by ayberktandogan** [ForFansubs/front-end#29]
# Öne Çıkarılmış Animeler güncellemesi

`react-slick` paketi kaldırılarak, yerine herhangi bir paket kullanmadan hazırlanacak yeni bir Öne Çıkarılmış Animeler kısmı.

## Yapılacaklar
- [x] Responsive test
- [ ] ~Resim konum ayarlama (Belki?)~
- [x] Tasarım güncellemeleri
- [ ] ~PV~
- [x] Mobilde kaydırarak önceki ve sonraki animeyi görme.

## Bilinen hatalar
- [x] Alttaki pagination butonlarının rengi mobilde üstüne basıldıktan sonra hover state'inde kalıyor. CSS düzeltmesi gerekiyor.
---------
![screencapture-localhost-3000-1585061299898 (1)](https://user-images.githubusercontent.com/42430762/77439109-b2108c00-6df7-11ea-9445-343f81558e17.png)
![screencapture-localhost-3000-1585060824597 (1)](https://user-images.githubusercontent.com/42430762/77439113-b3da4f80-6df7-11ea-868e-98eb8b1e4465.png)

**Comment by Hime-Dev** [comment]
Ellerine sağlık çok güzel duruyor fakat son bölümlerin uzun ince dikdörtgen yapısı bozulmasaydı çok daha güzel gözükebileceğini düşünüyorum.
