### ISSUE TITLE
[İSTEK] V3 için renk isteği

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/front-end#30]
## Özellik ayrıntıları
Etiket renkleri h6 ile renk alıyor bunu env den veya tema dosyalarından değiştirebileceğimiz bir alan olsa güzel olur. Yani demek istediğim gece modu var diye illaha gündüz modunda siyah renk kullanmak zorunda kalmayalım.

Kastedilmek istenen içinde ki yazılardır.
![sss](https://user-images.githubusercontent.com/57987392/77466122-da5db200-6e1a-11ea-8a0d-5fa56d4015a7.JPG)

## Aşağıdakileri doğruluyorum:
- [x] Sistemde böyle bir özelliğin olup olmadığını buraya yazmadan önce araştırdım.

**Comment by ayberktandogan** [comment]
https://github.com/ForFansubs/front-end/releases/tag/v2.6.2

**Comment by ayberktandogan** [comment]
`extra.js`'te main rengini değiştirirseniz, o renge uyumlu text rengini otomatik sağlıyor.

**Comment by Hime-Dev** [comment]
teşekkürler.
