### ISSUE TITLE
[GÜNCELLEME] Anime ve manga sayfa tasarımları

### ISSUE THREAD

**Issue by ayberktandogan** [ForFansubs/front-end#35]
Anime ve manga sayfalarının kullanımının kolaylaştırılması, yeniden tasarlanması.

### Yapılacaklar
- [x] Background bulunamadığında cover_art ile resim gösterimi.
- [x] İndirme linklerinin tasarımı.
- [x] Mobil uyum.
- [x] Eğer kullanıcı anime veya manga için logo koyarsa, normal text yerine logo gösterilmesi.
- [x] Toplu linkleri üstte göster.
- [ ] ~PV ?~
- [x] İndirme linklerine tıkladıktan sonra sayfanın herhangi bir yerine tıklanırsa container'ın kapanması.
- [x] İçerikte +18 türü varsa, kullanıcıya uyarı göster.

![screencapture-localhost-3000-ceviriler-anime-91-days-1589026650639](https://user-images.githubusercontent.com/42430762/81473638-7f382100-9208-11ea-9e94-4b80b44a34a3.png)

![screencapture-localhost-3000-ceviriler-anime-91-days-1589026802065](https://user-images.githubusercontent.com/42430762/81473650-937c1e00-9208-11ea-9572-5bd18211b8dc.png)

**Comment by ayberktandogan** [comment]
### Eksiklikler
- Header resmi bulunamadığında herhangi bir resim gösterilmiyor.
- İndirme linklerinin tasarımı?

![screencapture-localhost-3000-ceviriler-anime-fugou-keiji-balance-unlimited-1589027031024](https://user-images.githubusercontent.com/42430762/81473736-2f0d8e80-9209-11ea-8d1a-a7a5dfabc7cc.png)

**Comment by Hime-Dev** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/57987392/81481742-db1b9d80-923a-11ea-9a48-26e211c23bab.JPG)
pek çizemedim ama anlatmak istediğim toplu link eklendiği zaman sisteme en üste sabitleyecek şekilde olup altında <hr> gibi ince bir çizgi çizip eğer şahıs 1. bölüm, 2. bölüm şeklinde tek tek eklenirse gözükmesi hoş olabilir eğer toplu link eklenmemişse direk bölümler en üst kısım da gösterilir şeklinde ayarlanabilir birde ek olarak eğer izleme linki eklememiş ise kullanıcı direk izle butonun açılması insanları şaşırtabiliyor, o da düzeltilirse iyi olur Ek olarak 1. bölüm 2. bölüm şeklinde olan kutucuklar (toplu link değil.) birazcık daha büyültüp çevirmen ismi yazdırlabilir.

**Comment by ayberktandogan** [comment]
- [x] Background bulunamadığında cover_art ile resim gösterimi.
- [x] Toplu linkleri üstte göster.
----
![screencapture-localhost-3000-ceviriler-anime-black-clover-1589672564678](https://user-images.githubusercontent.com/42430762/82132417-2d832e00-97e8-11ea-97e9-5ed71da801c5.png)
![screencapture-localhost-3000-ceviriler-anime-black-clover-1589672575278](https://user-images.githubusercontent.com/42430762/82132419-2eb45b00-97e8-11ea-87f4-d20f6a640c05.png)

**Comment by Hime-Dev** [comment]
Güzel olmuş v3'e geçmeden buton sorunu da çözülürse (herhangi bir yere tıklayınca kapanma) daha iyi olur, birde merak ettiğim bir şey var acaba çevirmen ve encoder kısmı kaç isme kadar alıyor mesela 10 isim girdik diyelim aşağıya mı atacak yoksa cover arta doğru mu gidecek (10 tane encoder olmaz zaten sadece meraktan soruyorum) birde ilerleyen zamanlarda bu çevirmen isimlerini kullanıcı metionları gibi ekletebilirsin (yani direk tıklayınca onun profile atar tabi kullanıcı sistemi daha da aktif olunca çok zaman var daha bunun gibi bir şeye). Tek beğenmediğim kısım türleri ana sayfada olduğu gibi gösterebilirsin bir etiket içindeymiş gibi dikdörtgen sanki biraz çok fazla düz yazıya boğulmuş gibi duruyor sol taraf çevirmen adı, stüdyo vs olsun.

**Comment by ayberktandogan** [comment]
![screencapture-localhost-3000-ceviriler-anime-clannad-after-story-1590534460562](https://user-images.githubusercontent.com/42430762/82958795-edc5fe80-9fbe-11ea-9584-ab6f97fc46eb.png)

![screencapture-localhost-3000-ceviriler-anime-clannad-after-story-1590534479233](https://user-images.githubusercontent.com/42430762/82958787-e999e100-9fbe-11ea-950b-db8b523170a7.png)
