### ISSUE TITLE
[İSTEK]Manga Okuma Özelliği

### ISSUE THREAD

**Issue by Naitourufu** [ForFansubs/front-end#36]
# Özellik isteği

## Aşağıdakileri doğruluyorum:
- [x] Sistemde böyle bir özelliğin olup olmadığını buraya yazmadan önce araştırdım.
- [x] Üstteki kutucuklar yandaki gibi gözüküyor. (işiniz bittiğinde bu satırı silin lütfen...)

**Comment by ayberktandogan** [comment]
ForFansubs/node-server#15
