### ISSUE TITLE
[İSTEK] V3 İÇİN Bölümlerin Otomatik bir şekilde sıraya girmesi

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/front-end#37]
## Özellik ayrıntıları
Şöyle açıklayayım olayı mesela deneyecek olursanız x bir animenin ilk başta 1. bölüm değil de 10. bölümünü ekleyip sonrasında 1. bölümünü eklerseniz doğal olarak 10. bölümden sonra 1. bölüm gözükür ana sayfada fakat admin panelinde bakarsanız düzenleme kısmından bu anime bölümleri otomatik olarak 1 den başlayarak sıraya girmektedir eğer yapılabilirse v3 için otomatik düzenlenmesini isterim ön taraf için ek olarak admin panelinde düzenleme olayı biraz fazla işlevsiz olarak geliyor bana en azından tür + emeği geçen kişileri de yanlış eklendiyse oradan düzenlenmesini tercih ederim. Tabi yapılabiliyorsa
## Aşağıdakileri doğruluyorum:
- [x] Sistemde böyle bir özelliğin olup olmadığını buraya yazmadan önce araştırdım.

**Comment by ayberktandogan** [comment]
Ana sayfada böyle bir düzenin yapılması imkansız.

Anime düzenleme ekranına eklemeler yapıldı.
