### ISSUE TITLE
[İSTEK] Manga Okuma Sayfası

### ISSUE THREAD

**Issue by ayberktandogan** [ForFansubs/front-end#38]
# Özellik isteği

## Özellik ayrıntıları
Tekli ya da webtoon gibi okuma özellikleri olan, bütün bölümlerin tek bir sayfadan görüntülenebileceği bir manga okuma sayfası.

### Yapılacaklar:
- [x] Tekli ya da webtoon tarzında okuma, bu özelliği global statete tutma
- [ ] ~Sayfa listeleme~
- [x] ~Önceki ya da sonraki bölüm butonları~, bölüm listesinin yer alacağı kontrol kutusu
- [x] Yorum kutusu
- [x] Link üzerinden kalınan bölüm ve sayfanın hatırlanması
- [x] Lazyload
- [x] Sağ sol tuşlarında sayfa değişimi.
- [x] Sayfa değiştirme butonlarının ekranın sağına ve soluna sabitlenmesi.

**Comment by ayberktandogan** [comment]
ForFansubs/node-server#15

**Comment by ayberktandogan** [comment]
![screencapture-localhost-3000-ceviriler-manga-gakkougurashi-oku-1590596650453](https://user-images.githubusercontent.com/42430762/83046681-06322980-a050-11ea-9099-1707a4a32c40.png)

![screencapture-localhost-3000-ceviriler-manga-gakkougurashi-oku-1590591016722](https://user-images.githubusercontent.com/42430762/83046685-07fbed00-a050-11ea-9792-babccd090b66.png)

**Comment by Hime-Dev** [comment]
Butonlar üst de olmak yerine sayfanın sağ ve solunda olursa daha iyi olabileceğini düşünüyorum veya hiç buton koymadan manganın ilk sayfasında oto öğretici gibi bir şey ayarlanıp sayfanın sağ kısmına tıklarsanız ileri sol kısmına geri atacağını belirtmek daha iyi olur.

**Comment by ayberktandogan** [comment]
Selector kısmının mobilde native selector göstermesi gerekiyor.
