### ISSUE TITLE
[GÜNCELLEME] Ana Sayfa

### ISSUE THREAD

**Issue by ayberktandogan** [ForFansubs/front-end#39]
### Öne çıkarılmış animeler
- [x] Tasarımda yanlış bir şey var. Bulmamız gerekiyor. `keşke ne olduğunu bilsem` `sanırım padding ya da font` `o da değilmiş ama şimdi daha iyi gibi`

### Son eklenen bölümler
- [x] En Yeni Bölümler kısmı kalacak mı?
- [x] Hover animasyonunun hızını tekrar düşün.
- [x] Text arkaplan rengini daha belirgin yap?

### Son eklenen animeler ve mangalar
- [x] Popper componentını doldur.
- [ ] ~Popper en büyük boyutlara ulaştığında, konunun en altından başlayacak şekilde gradient ile overlay koy.~
- [x] onMouseEnter ve onMouseLeave yeterince güvenilir çalışmıyor. Alternatif ya da var olan sorunun çözümü?

### Genel
- [ ] ~Herhangi bir yere takvim eklemeye çalış?~
- [x] Belki genel olarak sayfa width'ini düşürürüz?

Material-UI günlükleri (popper.js): Material-UI `Popper` componentında arrow kullanmak için component içerisinde `<span className={classes.arrow} ref={setArrowEl} />` gibi bir arrow elementi oluşturup, ref'ini `Popper` modifiers prop objesi içerisindeki arrow.element'e tanımlaman gerekiyor. Ayrıca transition kullanamak istiyorsan, kullanacağın transition (örnek `Fade`) içerisinde ana bir element olması gerekiyor. `Transition` componentı `React.Fragment`tan hoşlanmıyor. Yani `Fade` içerisinde
```js
<>
    <div>Bla bla</div>
</>
```
kullanamazsın.
```js
<div>
    <div>Bla bla</div>
</div>
```
olur ama.

**Comment by ayberktandogan** [comment]
# 30.05.2020 güncellemesi

![screencapture-localhost-3000-1590855191103](https://user-images.githubusercontent.com/42430762/83333689-70dea180-a2aa-11ea-94a6-6ed28c81a0e7.png)

![screencapture-localhost-3000-1590855175164](https://user-images.githubusercontent.com/42430762/83333688-6e7c4780-a2aa-11ea-9a58-fe2360e47557.png)

**Comment by ayberktandogan** [comment]
### Popper örnek
![chrome_2020-05-30_19-28-41](https://user-images.githubusercontent.com/42430762/83333950-e5fea680-a2ab-11ea-831f-113d91e1ad58.png)

**Comment by ayberktandogan** [comment]
# 31.05.2020 Güncellemesi

![screencapture-localhost-3000-1590949164385](https://user-images.githubusercontent.com/42430762/83359716-bbcce780-a384-11ea-9dd6-293edf0639da.png)
![screencapture-localhost-3000-1590949177301](https://user-images.githubusercontent.com/42430762/83359719-bd96ab00-a384-11ea-8ad1-1a5fd57f3e13.png)

**Comment by Hime-Dev** [comment]
Bence eski tasarım daha hoştu. Fakat bu tasarım olacaksa boyutların yeniden göz atılmasını ve yeni bölümlerin altına 12. bölüm felan yazmak yerine bu tarz büyük tasarımlarda kullanıcı rahat ayırt etmesi adına bu anime cover'ını soldurup ortalı şekilde 12. bölüm felan yazıyorlar öyle bir şeyin daha iyi olacağını düşünmekteyim birde tasarım böyle olacaksa anime ve manga kısmını yukarıdaki slider gibi olması daha hoş olur  animeler otomatik olarak sola doğru kayar maksat kullanıcı farklı animeleride görsün

**Comment by ayberktandogan** [comment]
Eski tasarım kötü duruyordu, istediğim tasarımı yakalayamamıştım çünkü. Bu yeni tasarımda ana hatları yakaladığımı düşünüyorum ama hala içime sinmeyen detaylar var, zamanla çözebileceğimi düşünüyorum.

O slider olayını sunucu ve ön taraf performansını test ettikten sonra düşüneceğim. Şu anda zaten ana sayfada çok şey var. Daha fazla şey eklersem sorun çıkarabilir.

**Comment by Hime-Dev** [comment]
evet haklsınız elinize sağlık tekrardan v3 ün çıkışını dört gözle bekliyorum.
