### ISSUE TITLE
Gelecekte güzel olabilecek istekler forfansubs. 

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/front-end#4]
Merhaba gelecekte gelse fena olmaz dediğim bir kaç özellik var ne kadarı yapılabilir bir fikirim yok burada dediklerimi önceden düşünmüş olabilirsiniz sadece fikrimi belirtmek amaçlı yazıyorum.

1-Bazı animelerde mal dan çektiği verilerde fall kısmı sonbahar 2019 vs belirtiyor bunu en iyi arama kısmına girince görebiliyorsunuz. fakat bir çoğunda da bilgi bulunamadı diyor bunu sonradan admin panelinden vs değiştirilebilecek veya eklenebilecek şekilde ayarlanması olabilir.

2-Bu anime konularında yan özet/indirme kısmında 1.bölüm,toplu link kısaca butonlara tıklandığında tekrar üstüne tıklandığında kapanıyor fakat bu küçük ekran veya mobil için sıkıntı olabiliyor tavsiyem bir kez tıklandıktan sonra sayfada herhangi bir yere tıkladığınızda kapanması daha hoş olabilir.

3-Birinci madde de dediğim istekdeki fall kısmı sonbahar vs konu özet/indirme sayfasında anime adından sonra değilde soldaki çevirmen stüdyo vs yazan yerde olursa daha hoş olabilir çünkü bazı animelerde isimleri çok uzun ve bu uzunluklardan dolayı özet yazısının üstüne kayıyor.

4-Discord embbedaki coverartlar discorda paylaştığı zaman bot resim boyutu biraz küçük kalıyor bunun büyültülebilir azcıkdaha

5-Eski openload rapidvideo vs kaynaklar kapandığı için yeni kaynaklar fena olmaz ben kendim bunda bir kaç adet  manuel olarak ekledim isteyen olursa atarım. Zor bir şey değil zaten eklemek.

6-Kayıt olan kullanıcılar için avatar ve izlediklerim takipte olduklarım sayfası veya indireceklerim vs...

7-Anime konularında her headeri mal dan çekmiyor farklı bir api ile headerlar desteklenebilir.

8-dfile,bdupload siteleri için player desteği

9-Birde psycho-pass3 filmi vs gibi aşırı uzun adlı animelerde too long hatası veriyor api ben çözdüm sorunu fakat 0 dan indirip kulanacaklar için hala sorunlu

bu çalışma hala devam etmekte olan bir çalışma olduğunu biliyorum sadece benim dediklerim istek ve tavsiye olarak görünüz hani adam o kadar yapmış vs demeyiniz evet eline sağlık güzel yapmış benim amacım olabilecek her yönüyle ne kadar geliştrilebilir aklımdakileri yazdım amacım yargılamak vs eleştirmek değil. Çalışmada başarılar dilerim.

**Comment by ayberktandogan** [comment]
#8 
ForFansubs/front-end-admin#2
ForFansubs/node-server#3
