### ISSUE TITLE
MOBİL [HATA]

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/front-end#41]
Mobil kısmında v3 betada hata var gösterimde
![ff](https://user-images.githubusercontent.com/57987392/85888658-aff10b80-b7f2-11ea-868e-69e21981a43a.jpeg)

**Comment by Hime-Dev** [comment]
Birde hata denmez ama kasıtlı yapılıp yapılmadığını bilmiyorum anime sayfalarının ve ana sayfadaki mevsim kısımlarının indirme linkleri başlığı gibi keşke belirgin olsaymış siyah renk için neyse fakat beyaz renkte çok zor ayırt ediliyor ek olarak ana sayfada slider kısmı sağ ve sola mobilde kaydırma yapılabilse daha güzel olacağını düşünmekteyim.

**Comment by ayberktandogan** [comment]
Browser'da masaüstü modunun açık kalıp kalmadığını kontrol edebilir misiniz acaba? Bende herhangi bir sorun gözükmüyor çünkü.
![Screenshot_20200626-214556_Chrome](https://user-images.githubusercontent.com/42430762/85890813-c4cf9e00-b7f6-11ea-8740-efd6e98a99f0.png)

Anime sayfasındaki mevsim kısmının rengini açık tema için değiştirdim az önce. Ana sayfadaki önce çıkarınlar kısmını da mobilde kaydırabilir yapacağım versiyonu master'a almadan önce.

**Comment by Hime-Dev** [comment]
evet masaüstü modun da kalmış olabilir başka telefonlardan baktım bir sıkıntı yoktu. Arama kısmında gündüz modunda isimle arayın yazısı beyaz oluyor ve hem göz kamaştırıcı hemde belli olmuyor siyah olursa daha iyi olur. Birde tür seçimlerinde hepsini seçtikten sonra  sıfırlamak istediğimizde tek tek üstüne basıyoruz bunun yerine filtreleri sıfırla gibi bir şey olursa çok iyi olur.  Birde butonlara da farklı yere tıklayınca kapanıyor güzel olmuş fakat disqus kısmının oraya tıklayınca kapanmıyor disqus otomatik bölüm konularını açıp yerleştirdiği için onunla alakalı bir şey olduğunu düşünmekteyim bu sefer gerçekten son olarak :) izle kısmında v3 emektarların olduğu kısımda anime adı + resim gelmiş ben biraz daha sistemde ön tarafta hem daha şık gözükeceğine inandığım ve arka tarafta da yönetici için kolay  olacak iki şey düşünmekteyim birincisi anime adının altına direk Emektarlar:
hime
hime
şeklinde olursa daha güzel olur gelelim yönetici için kolay olacak kısma bölümleri açarken "e kadar" (Örnek 1'den 23'e kadar) bölüm aç ve bölümü açtıktan sonra toplu linkler hariç tüm bölümleri tek seferde gizleme veya gösterme kısmı güzel olabileceğini düşünmekteyim bu e kadar bölüm açta discord üzerinde şuradan şuraya kadar bölümler eklendi şeklinde tek mesaj olursa güzel olacağını düşünmekteyim.
