### ISSUE TITLE
[SORU] Son Güncellemede ki Sitemap Durumu

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/front-end#45]
Şimdi github üzerinde özellik yada hata raporu oluşabildiği için en yakın olanı seçtim. 
Soracağım soru şu: Bu 40 dk önce yayınlanan sayfa ekleme güncellemesinde sitemap config dosyası üzerinde herhangi bir işlem yapmamıza gerek var mı ve otomatik olarak react helmet kodları yerleştiriliyor mu ? , Ben kendim eklerken sitemap configinde eklediğim sayfayı da eklemiştim de bir sormak istedim.

**Comment by ayberktandogan** [comment]
Sitemapten kastınız ne anlamadım. v3'le gelen otomatik sitemap oluşturmasıysa, orayla ilgili bir şey yapmanıza gerek yok.

`./src/config/front-routes.js`'ten bahsediyorsanız da, hayır oraya da bir şey eklemenize gerek yok. Sadece `./src/pages/extra-pages/index.js`'i gerektiği gibi doldurun. Gerisini sistem hallediyor.

Oluşturduğunuz sayfalarda Helmet gibi import edilmesi gereken hiçbir paket otomatik olarak eklenmiyor. Onlardan kullanıcı sorumlu. Kendiniz import ederek kullanabilirsiniz. Ayrıca oluşturacağınız sayfalara kendi kullandığım componentları da ekleyebilirsiniz. Bunların herhangi bir dökümanı yok ancak, sayfalara bakarsanız hazır componentlar görebilirsiniz.

```js
import React from 'react'
import { Typography } from '@material-ui/core'

import Metatags from '../../../../components/helmet/index'
import ReactGA from 'react-ga'

export default function DestekOl() {
    ReactGA.pageview(window.location.pathname)

    return (
        <>
            <Metatags title="Destek Ol - ForFansubs" desc="Bize destek olun" url="/destek-ol" type="website" keywords="destek,ol,forfansubs" image="/logo.png" />
            <Typography>
                Destek Ol
            </Typography>
        </>
    )
}
```

Mesela yukardaki örnek, Helmet taglarını otomatik oluşturup, Google Analytics'e bilgi yollayabiliyor. (keywords ve image kısmı zorunlu değil.)

Bunun gibi componentları `./src/components` kısmındaki dosyalardan bulabilirsiniz. Ya da sayfalara bakarak.

**Comment by Hime-Dev** [comment]
PATH:\node-server\config\sitemap-generator.js
![Ekran Alıntısı](https://user-images.githubusercontent.com/57987392/86176820-3af13f00-bb2e-11ea-80ff-ff11164343a4.PNG)
React helmet açıklamanız için teşekkürler sitemapten kastım resimdeki alandı.

**Comment by ayberktandogan** [comment]
Oradaki düzenlemeler hala takip ediliyor, o yüzden elle değiştirmek çok iyi bir fikir değil.

Zaten statik sayfa olduğu için, yukardaki örnekte attığım gibi ReactGA.pageview fonksiyonunu kullanırsanız Google aramalarına ekliyor sayfayı.

**Comment by Hime-Dev** [comment]
tamamdır teşekkürler.
