### ISSUE TITLE
[İSTEK] Ana Sayfa Tasarım Ufak Öneri

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/front-end#46]
Anime ve Mangaların şu kısma doğru kayması güzel olabilir yani orada da anime bölümleri olsa veya manga fena olmaz çünkü biraz boş duruyor itici gibi tabi sadece öneri istek olarak değerlendirmeyin.

![333](https://user-images.githubusercontent.com/57987392/87100021-fb280700-c253-11ea-8d80-57993e426911.PNG)

**Comment by ayberktandogan** [comment]
ForFansubs/node-server#44

- [ ] API yolunda service-worker silinmesini kaldır.
- [ ] Bölüm kısımlarını CSS Grid ile tekrardan düzenle.
