### ISSUE TITLE
[HATA] Footer.Js

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/front-end#47]
# Hata raporu

## Aşağıdakileri doğruluyorum:
- [x] Kodda kendi değiştirdiğim bir şey yüzünden aldığım bir hata değil.
- [x] front-end'in son versiyonunu kullanıyorum.

## Sorunlar
Footer item.js de eğer çok fazla aray eklenirse yan yana atıyor belli bir array'den sonra aşağıya atılmasının sağlanması daha iyi olacağını düşünüyorum.

**Comment by ayberktandogan** [comment]
#46
