### ISSUE TITLE
[HATA] Ana Sayfa Manga Kısmı

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/front-end#51]
# Hata raporu

## Sistem Bilgisi
Son Update'ler
## Aşağıdakileri doğruluyorum:
- [x] Kodda kendi değiştirdiğim bir şey yüzünden aldığım bir hata değil.
- [x] front-end'in son versiyonunu kullanıyorum.

## Sorunlar
Ana sayfada manga kısmı 2 manga fazladan gösteriyor kasıtlı mı yapıldı fikrim yok belirtmek istedim.

![Ekran Alıntısı](https://user-images.githubusercontent.com/57987392/87359477-8d8c1b80-c570-11ea-850c-171ebfbf0208.PNG)

**Comment by ayberktandogan** [comment]
ForFansubs/node-server#52
