### ISSUE TITLE
🌸 v4.*.* Yol Haritası

### ISSUE THREAD

**Issue by ayberktandogan** [ForFansubs/front-end#54]
# v4.\*.\* Yol Haritası

Bu issue kapatılana kadar https://github.com/ForFansubs/front-end/tree/dev üzerinde devam eden değişiklikleri ele alacak.

## Çıkış tarihi
TBD

## Yapılacaklar
- [ ] SVG Logo desteği. ForFansubs/node-server#25 
- [x] Anime takvim. #31 
- [ ] ~Kullanıcı sayfaları.~ #18
- [x] Dil desteği. #57 
## Önemli duyurular 💥💥💥
- 4.\*.\* versiyonuna tam olarak geçiş yapıldığında, 3.\*.\* versiyonu için ayrı bir branch açılıp, `master` branchi 4.\*.\*'a geçirilecek.

## Önemli Değişiklikler (v3.\*.\* --> v4.\*.\*) 💔
- `cron`, `react-async-hook`, `react-parallax`, `rellax`, `remarkable`, `react-toastify` paketleri kaldırıldı.
- `react-device-detect` paketi eklendi.

### Database değişiklikleri
WIP.

## Yenilikler
WIP.

## Güncellenen paketler
WIP.

**Comment by Hime-Dev** [comment]
V4 için manga kısmına harici site ekleyebilme örneğin sayfa yükleme kısmından kendi sunucumuza yükleyebileceğimiz gibi başka siteden yükle gibi bir seçenek olup site üzerinden de yükleme yapabilirsek güzel olacağını inanmaktayım ek olarak raiting, link count ve views gibi ekstra özellikler gelirse güzel olacağını düşünmekteyim. Son olarak düzenleme kısmındaki kriterler genişlerse güzel olur bazı alanları düzenlemeye izin vermiyor onlarda açık olsa harika olurdu.

**Comment by ayberktandogan** [comment]
Harici site eklemekten kasıt ne anlamadım. Google Drive vb. sitelere yükleyip, sayfaları oradan almayı mı düşünüyorsunuz?

Konuların kaç kez görüntülendiği, indirme linklerine ne kadar tıklandığı ya da bölümlerin ne kadar izlendiği/okunduğu sayılarını tutacak sistem için birkaç şey düşünüyorum. v4'e yetiştirebilirsem yapacağım. Yoksa v5'e kalacak.

**Comment by Hime-Dev** [comment]
Harici site eklemekten kasıt ne anlamadım. Google Drive vb. sitelere yükleyip, sayfaları oradan almayı mı düşünüyorsunuz?

Bu soruya şöyle cevap vereyim eğer yapılabilirse drive gibi yere yüklenip iframe olarak gösterme güzel olur onun haricinde ekstra depolama alanı gösterebilme mantığında demiştim atıyorum bir tane sunucuda alan doldu diyelim gidip  mangaları şu ftp adresinden şu suncuya ekle şekilnde ekstra path göstermeyi kastetmiştim.
