### ISSUE TITLE
[İSTEK] Etikete Göre Uyarı Anime/Manga

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/front-end#60]
## Özellik ayrıntıları
Türe göre uyarı penceresi, örneğin ecchi gibi bir etiketi varsa anime/manganın girince karşısına bu anime +16/+18 yaş kişiler için uygundur vs gibi bir yazı çıkması

## Aşağıdakileri doğruluyorum:
- [x] Sistemde böyle bir özelliğin olup olmadığını buraya yazmadan önce araştırdım.

**Comment by ayberktandogan** [comment]
+18 türü için bu uyarı var.
