### ISSUE TITLE
[İSTEK] V4 Default tema seçme .env üzerinden

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/front-end#64]
# Özellik isteği
Default tema seçme .env üzerinden

## Özellik ayrıntıları
.env üzerinden default tema seçilebilmesi demek istediğim. Zaten siyah veya beyaz diye 2 tema var değişiyor renkleri fakat benim dediğim gizliden vs açıldığında her zaman beyaz ile açılmakta site bunun ayarının yapılabilmesi.

## Aşağıdakileri doğruluyorum:
- [x] Sistemde böyle bir özelliğin olup olmadığını buraya yazmadan önce araştırdım.

**Comment by ayberktandogan** [comment]
Kullanıcı ilk kez sayfaya girdiği zaman tarayıcı/sistem temasına bağlı olarak seçiliyor tema. Sonrasında kaydedilip bir daha oradan kullanılıyor. Bu kontrol gizli modda da çalıştığı için .env'e bağlı herhangi bir seçeneği gereksiz buluyorum. Kullanıcı hangisini tercih ediyorsa onun olması daha mantıklı.
