### ISSUE TITLE
[HATA] MOTD Anime ve Manga Bölüm Hatası

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/front-end#67]
# Hata raporu

## Sistem Bilgisi
En son güncelleme ve versiyon.

## Aşağıdakileri doğruluyorum:
- [x] Kodda kendi değiştirdiğim bir şey yüzünden aldığım bir hata değil.
- [x] front-end'in son versiyonunu kullanıyorum.
## Sorunlar

Duyuru eklerken bölüm sayfalarına eklersek bir sorunla karşılaştı demekte.

**Comment by ayberktandogan** [comment]
MOTD eklendikten sonra çıkan hatanın kaynağını bulamadığım için v3'te öyle bırakmıştım. Aslında işleyişte sorun yok.

**Comment by Hime-Dev** [comment]
tamamdır teşekkürler.
