### ISSUE TITLE
Adsense + Toplu Link Kısmı

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/front-end#7]
Site üzerine bir kaç tane özelleştirilebilir reklam alanı eklense fena olmaz.  (label kullanmadım istek labeli ekleyecektim.)

Extra: Birde site içinde ki toplu link kısmını nasıl aktive edebilirim ? front ende

**Comment by ayberktandogan** [comment]
Ana sayfadaki Toplu Link kısmında bölüm göstermek için, herhangi bir animeye toplu türünde bölüm numarası 0 olacak şekilde yeni bir bölüm açmanız gerekiyor. Bundan sonra bölüm, ana sayfada gözüküyor.

Reklam kısımları 2. planda şu anda. Ondan önce eklemek istediğim farklı şeyler var.

**Comment by Hime-Dev** [comment]
cevabınız için teşekkürler birde ekstra olarak eklemek istediklerinizden sonra ona etiketi de ekler misiniz zamanında eklemiştim fakat ön sayfaya bölüm ona diye düşse bile başında link olarak bolum/ona diye ekliyordu sonrasında kaldırmıştım. İnce bir detay belki ama hoş olabilir birde birazdan bir kaç video kaynağı sizin eklemediğiniz ve tr için ok.ru yu odnok yapmıştım onları atacağım. (odnok yapma sebebi bazı ttnet gibi sağlayıcılarda artık ok.ru açılmyor. odnok.ru dan giriyor.)

**Comment by ayberktandogan** [comment]
#8
