### ISSUE TITLE
Öğeyi denetle kaynak kodların gözükmesi.

### ISSUE THREAD

**Issue by memedhacker** [ForFansubs/front-end#88]
https://www.youtube.com/watch?v=5hKs5PoUC9E

yukarıdaki videoyu izledikten sonra aklıma siz geldiniz ve "ulan acaba" deyip bir bakıverdim. Gerçekten de öğeyi denetle yapıp kaynak kısmına gelince JS dosyaları gözüküyor. Sizin için problem teşkil eder mi bilemiyorum, React'tan da pek anlamam ama bilgilendirmek istedim.

**Comment by ayberktandogan** [comment]
Merhaba,

Endişeniz için teşekkürler ancak ForFansubs projesinin bütün kaynak kodu, herkese açık şekilde bu reponun bağlı olduğu organizasyonda bulunmaktadır zaten. Bu nedenle Dev Tools'dan okunabilen kaynak kodun herhangi bir zararı bulunmamaktadır.
