### ISSUE TITLE
Dinamik Meta Tag Başlık Sorunu

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/front-end#9]
Dinamik meta tag olarak değişiyor fakat yarım değişiyor Türkçe İzle & İndir olacağı yerde Türkçede kalıyor.
![fsffs](https://user-images.githubusercontent.com/57987392/76154592-045f6680-60f0-11ea-8f64-0310403e4742.JPG)
2. Resimi atma sebebim başlıkta herhangi bir sorun olmaması vs.

![fsfs](https://user-images.githubusercontent.com/57987392/76154590-032e3980-60f0-11ea-8359-c313aeb398bc.JPG)

**Comment by ayberktandogan** [comment]
.env içerisinde **REACT_APP_INDEX_TITLE_TEXT** değerini "Türkçe İzle & İndir" şeklinde girdiğinizden emin misiniz? Az önce bu şekilde buildlediğimde herhangi bir sorunla karşılaşmadım.

**Comment by Hime-Dev** [comment]
Türkçe Anime ve Manga Çeviri Topluluğu diye build ediyordum site başlığının sonuna eklediği için sanırsam public içindeki title Site Adı Türkçe Anime ve Manga Çeviri Topluluğu şeklinde yapıp  REACT_APP_INDEX_TITLE_TEXT değerini "Türkçe İzle & İndir"  böyle yapmam lazım cevabınız için teşekkürler birde og datalarında eskiden kalma 512.png var haberiniz olsun isterseniz onu logo.png diye düzeltiniz.
![fsfs](https://user-images.githubusercontent.com/57987392/76154920-97e76600-60f5-11ea-9fda-64d684ec4406.JPG)

**Comment by ayberktandogan** [comment]
Ah, teşekkürler.

#8

**Comment by Hime-Dev** [comment]
Kusura bakmayın tekrardan rahatsızlık veriyorum dediğiniz gibi yapıp build ettim fakat sonuç yine aynı.

![fsfssfsf](https://user-images.githubusercontent.com/57987392/76155089-50aea480-60f8-11ea-949b-2a0be824a148.JPG)
İsterseniz sitemi live olarak kontrol edebilirsiniz.

**Comment by ayberktandogan** [comment]
Sorun indexte sandım. Yaşadığınız şey intentional. Anime konularında bölüm olmayınca "İzle ve İndir" kısmını eklemiyor. .env'deki değer, sadece index'te kullanılıyor.

**Comment by Hime-Dev** [comment]
"Anime konularında bölüm olmayınca "İzle ve İndir" kısmını eklemiyor. .env'deki değer, sadece index'te kullanılıyor." Evet sadece indexi etkiliyormuş. Kusuruma bakmayında şimdi anime konularında ki title in Türkçe olarak kalması devamının gelmesi kasıtlı olarak yaptığınız bir şey mi ? pek anlayamadım. Sorunum tam olarak anime konularında anime isminden sonra izle ve indir gelmemesi.

**Comment by ayberktandogan** [comment]
Evet kasıtlı. pages/ceviriler/anime/index.js:79

**Comment by Hime-Dev** [comment]
Anladım ilgi ve alakanız için teşekkürler.
